[build]
  base = "frontend" # Base directory where Netlify installs dependencies and runs the build command
  command = "npm run build" # Build command for the React app
  publish = "dist" # Publish directory for the built React app

[functions]
  directory = "../backend/functions" # Directory where your Netlify functions are located
  external_node_modules = ["serverless-http"] # Ensure serverless-http is included in your function bundle
  node_bundler = "esbuild" # Bundler for the serverless functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
