[build]
  functions = "backend/functions"
  publish = "frontend/dist" # Assuming 'dist' is the build output folder of your React app

[functions]
  external_node_modules = ["serverless-http"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
