[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist" # The output directory relative to the base directory

[functions]
  directory = "backend/functions"
  external_node_modules = ["express", "axios", "cors", "serverless-http"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
